// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheSpender.DAL;
using TheSpender.DAL.Entities.Categories;

#nullable disable

namespace TheSpender.DAL.Migrations
{
    [DbContext(typeof(SpenderDbContext))]
    [Migration("20250816092839_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "categoryTypes", new[] { "expense", "income" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "category_types", new[] { "income", "expense" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheSpender.DAL.Entities.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.HasDiscriminator().HasValue("BaseEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TheSpender.DAL.Entities.Categories.Category", b =>
                {
                    b.HasBaseType("TheSpender.DAL.Entities.BaseEntity");

                    b.Property<CategoryTypes>("CategoryType")
                        .HasColumnType("\"categoryTypes\"");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Category");
                });

            modelBuilder.Entity("TheSpender.DAL.Entities.Operations.Operation", b =>
                {
                    b.HasBaseType("TheSpender.DAL.Entities.BaseEntity");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OperationNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SumOfMoney")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("IsDeleted")
                                .HasColumnName("Operation_IsDeleted");

                            t.Property("UserId")
                                .HasColumnName("Operation_UserId");
                        });

                    b.HasDiscriminator().HasValue("Operation");
                });

            modelBuilder.Entity("TheSpender.DAL.Entities.Tags.Tag", b =>
                {
                    b.HasBaseType("TheSpender.DAL.Entities.BaseEntity");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("CategoryId")
                                .HasColumnName("Tag_CategoryId");

                            t.Property("Name")
                                .HasColumnName("Tag_Name");
                        });

                    b.HasDiscriminator().HasValue("Tag");
                });

            modelBuilder.Entity("TheSpender.DAL.Entities.Users.User", b =>
                {
                    b.HasBaseType("TheSpender.DAL.Entities.BaseEntity");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("User");
                });
#pragma warning restore 612, 618
        }
    }
}
